version: '3.3'
services:
  app:
    build: backend/
    volumes:
      - "./backend:/app"
    ports:
      - "42069:42069"
  db:
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
      - 8000:8000
  